# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'codelasak.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.before = QtWidgets.QPushButton(self.centralwidget)
        self.before.setGeometry(QtCore.QRect(620, 210, 181, 71))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.before.setFont(font)
        self.before.setAutoFillBackground(False)
        self.before.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255,255, 255)")
        self.before.setDefault(False)
        self.before.setFlat(False)
        self.before.setObjectName("before")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(590, 50, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.after = QtWidgets.QPushButton(self.centralwidget)
        self.after.setGeometry(QtCore.QRect(620, 350, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.after.setFont(font)
        self.after.setAutoFillBackground(False)
        self.after.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255,255, 255)")
        self.after.setDefault(False)
        self.after.setFlat(False)
        self.after.setObjectName("after")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(20, 0, 521, 551))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("img\Before.png"))
        self.photo.setScaledContents(False)
        self.photo.setObjectName("photo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionNew)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.after.clicked.connect(self.show_after)
        self.before.clicked.connect(self.show_before)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.before.setText(_translate("MainWindow", "Before"))
        self.label1.setText(_translate("MainWindow", "CyroDeep V0.1 Beta"))
        self.after.setText(_translate("MainWindow", "After"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new test"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
    
    def show_before(self):
        self.photo.setPixmap(QtGui.QPixmap("img\Before.png"))

    def show_after(self):
        self.photo.setPixmap(QtGui.QPixmap("img/After.png"))


    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
